# Generated by Django 5.1.4 on 2024-12-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_administratif', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificat', models.CharField(max_length=50)),
                ('date_emission', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('duree_arret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_examen', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('resultat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamenBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField()),
                ('values', models.JSONField()),
                ('graphique_tendance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_infirmier', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laborantien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laborantien', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medecin', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('voie_administration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_radiologue', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consultation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('observations', models.TextField()),
                ('examens', models.ManyToManyField(related_name='consultations', to='shared_models.examen')),
            ],
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compte_rendu', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('contenu', models.TextField()),
                ('auteur', models.CharField(max_length=100)),
                ('observations_complementaires', models.TextField()),
                ('recommandations', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.consultation')),
                ('examen_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.examen')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_image', models.CharField(max_length=100)),
                ('fichier_image', models.FileField(upload_to='radiologie/')),
                ('compte_rendu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shared_models.compterendu')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordonnance', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('doses', models.JSONField()),
                ('duree_traitement', models.CharField(max_length=100)),
                ('medicaments', models.ManyToManyField(related_name='ordonnances', to='shared_models.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_securite_sociale', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('personne_contact', models.CharField(max_length=100)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='shared_models.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dossier', models.CharField(max_length=50)),
                ('date_ouverture', models.DateField()),
                ('antecedents', models.JSONField()),
                ('certificats_medicaux', models.ManyToManyField(related_name='dossiers', to='shared_models.certificatmedical')),
                ('consultations', models.ManyToManyField(related_name='dossiers', to='shared_models.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resume', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('contenu', models.TextField()),
                ('antecedents', models.JSONField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_models.resume'),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soin', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('observations', models.TextField()),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.infirmier')),
                ('medicaments_administres', models.ManyToManyField(related_name='soins', to='shared_models.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='soins',
            field=models.ManyToManyField(related_name='consultations', to='shared_models.soin'),
        ),
    ]
