# Generated by Django 5.1.4 on 2025-01-05 11:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administratif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_administratif", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_examen", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("resultat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Laborantien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_laborantien", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=100)),
                ("voie_administration", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Radiologue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_radiologue", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("administratif", "Administratif"),
                            ("patient", "Patient"),
                            ("medecin", "Medecin"),
                            ("infirmier", "Infirmier"),
                            ("radiologue", "Radiologue"),
                            ("laborantien", "Laborantien"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="user_set_custom", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permission_users",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_consultation", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("motif", models.CharField(max_length=255)),
                ("observations", models.TextField()),
                (
                    "examens",
                    models.ManyToManyField(
                        related_name="consultations", to="shared_models.examen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteRendu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_compte_rendu", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("contenu", models.TextField()),
                ("auteur", models.CharField(max_length=100)),
                ("observations_complementaires", models.TextField()),
                ("recommandations", models.TextField()),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.consultation",
                    ),
                ),
                (
                    "examen_associe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.examen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Infirmier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_infirmier", models.CharField(blank=True, max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamenBiologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters", models.JSONField()),
                ("values", models.JSONField()),
                ("graphique_tendance", models.CharField(max_length=255)),
                (
                    "examen",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens_biologiques",
                        to="shared_models.examen",
                    ),
                ),
                (
                    "laborantien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens_biologiques",
                        to="shared_models.laborantien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_medecin", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("specialite", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificatMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_certificat", models.CharField(max_length=50)),
                ("date_emission", models.DateField()),
                ("motif", models.CharField(max_length=255)),
                ("duree_arret", models.CharField(max_length=100)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.medecin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_ordonnance", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("doses", models.JSONField()),
                ("duree_traitement", models.CharField(max_length=100)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordonnances",
                        to="shared_models.consultation",
                    ),
                ),
                (
                    "medicaments",
                    models.ManyToManyField(
                        related_name="ordonnances", to="shared_models.medicament"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_securite_sociale", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(default="1900-01-01")),
                ("adresse", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("personne_contact", models.TextField(blank=True, default="[]")),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                ("gender", models.BooleanField(default=True)),
                (
                    "medecins_traitants",
                    models.ManyToManyField(
                        blank=True, related_name="patients", to="shared_models.medecin"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examen",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="shared_models.patient",
            ),
        ),
        migrations.CreateModel(
            name="DossierPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_dossier", models.CharField(max_length=50)),
                ("date_ouverture", models.DateField()),
                ("antecedents", models.JSONField()),
                (
                    "certificats_medicaux",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dossiers",
                        to="shared_models.certificatmedical",
                    ),
                ),
                (
                    "consultations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dossiers",
                        to="shared_models.consultation",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier",
                        to="shared_models.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="certificatmedical",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificats_medicaux",
                to="shared_models.patient",
            ),
        ),
        migrations.CreateModel(
            name="ExamenRadiologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_image", models.CharField(max_length=100)),
                ("fichier_image", models.FileField(upload_to="radiologie/")),
                (
                    "compte_rendu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.compterendu",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens_radiologiques",
                        to="shared_models.examen",
                    ),
                ),
                (
                    "radiologue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens_radiologiques",
                        to="shared_models.radiologue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_resume", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("contenu", models.TextField()),
                ("antecedents", models.JSONField()),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.medecin",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="shared_models.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="resume",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shared_models.resume",
            ),
        ),
        migrations.CreateModel(
            name="Soin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_soin", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("observations", models.TextField()),
                (
                    "infirmier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared_models.infirmier",
                    ),
                ),
                (
                    "medicaments_administres",
                    models.ManyToManyField(
                        related_name="soins", to="shared_models.medicament"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="shared_models.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="soins",
            field=models.ManyToManyField(
                related_name="consultations", to="shared_models.soin"
            ),
        ),
    ]
