# Generated by Django 5.1.4 on 2024-12-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medecin_traitant',
        ),
        migrations.AddField(
            model_name='certificatmedical',
            name='auteur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shared_models.medecin'),
        ),
        migrations.AddField(
            model_name='certificatmedical',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='certificats_medicaux', to='shared_models.patient'),
        ),
        migrations.AddField(
            model_name='examen',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='shared_models.patient'),
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='examen',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examens_biologiques', to='shared_models.examen'),
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='laborantien',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examens_biologiques', to='shared_models.laborantien'),
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='examen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examens_radiologiques', to='shared_models.examen'),
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='radiologue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examens_radiologiques', to='shared_models.radiologue'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='shared_models.consultation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medecins_traitants',
            field=models.ManyToManyField(blank=True, related_name='patients', to='shared_models.medecin'),
        ),
        migrations.AddField(
            model_name='resume',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='shared_models.patient'),
        ),
        migrations.AddField(
            model_name='soin',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='shared_models.patient'),
        ),
        migrations.AlterField(
            model_name='dossierpatient',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='shared_models.patient'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='auteur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shared_models.medecin'),
        ),
    ]
