# Generated by Django 5.1.4 on 2025-01-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_infirmier_user_medecin_user_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
