# Generated by Django 5.1.4 on 2025-01-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_patient_qr_code_alter_patient_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='certificats_medicaux',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='shared_models.certificatmedical'),
        ),
        migrations.AlterField(
            model_name='dossierpatient',
            name='consultations',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='shared_models.consultation'),
        ),
    ]
