# Generated by Django 5.1.4 on 2025-01-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_alter_infirmier_id_infirmier_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenbiologique',
            name='consultation',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='shared_models.consultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='consultation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shared_models.consultation'),
            preserve_default=False,
        ),
    ]
