# Generated by Django 5.1.4 on 2025-01-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_examenbiologique_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenbiologique',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_models.consultation'),
        ),
    ]
