# Generated by Django 5.1.4 on 2025-01-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0008_alter_examenradiologique_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenbiologique',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='examenradiologique',
            name='consultation',
        ),
    ]
