# Generated by Django 5.1.4 on 2025-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0009_remove_examenbiologique_consultation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="personne_contact",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
